#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <hostname>"
    exit 1
fi

host_process=$(ps aux | grep "mininet:$1" | grep -v grep)
if [ -z "$host_process" ]; then
    echo "No mininet process found for $1"
    exit 1
fi

host_pid=$(echo $host_process | awk '{print $2}')

sudo mnexec -a $host_pid /bin/bash